### ISSUE TITLE
NodejsDeployment from 'deploy-time-build' causes deploy to fail

### ISSUE THREAD

**Issue by elektracodes** [aws-samples/serverless-full-stack-webapp-starter-kit#2]
Hello and thank you for the stack. Unfortunately the NodejsDeployment throws error. 

`Received response status [FAILED] from custom resource. Message returned: Command failed: npm ci`

Locally, `npm ci` works fine.

Do you have an idea why? How can I debug this?

**Comment by tmokmss** [comment]
Hi @elektracodes thank you for reporting! Have you added any dependencies? If possible, could you share package.json?

**Comment by elektracodes** [comment]
I cloned the project again and updated aws-cdk and it works fine, so the issue is locally. Thank you for taking the time to answer
